// Copies the parts of the prototype that must stay identical to production
// out of the production source: design tokens, both languages' strings, the
// icon paths, the QR encoder, the fonts, and the visitor pages' styles and
// copy from internal/server. Run it after any of those change; `--check`
// fails instead of writing when the copies have drifted.
//
//   node designs/sani/tools/sync.mjs           write src/gen/* and src/fonts/*
//   node designs/sani/tools/sync.mjs --check   exit 1 if anything differs
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const project = resolve(here, '..');
const repo = resolve(project, '../..');
const web = join(repo, 'web');
const check = process.argv.includes('--check');

const read = (p) => readFileSync(p, 'utf8');
const banner = (src) => `/* Generated by tools/sync.mjs from ${src}. Do not edit; edit the source and re-run. */\n`;

/** Tokens: app.css verbatim, plus theme scopes so a board can be light or dark inside any page. */
function tokens() {
  const css = read(join(web, 'src/app.css'));
  const dark = css.match(/:root\[data-theme="dark"\] \{([\s\S]*?)\n\}/);
  const light = css.match(/:root \{([\s\S]*?)\n\}/);
  if (!dark || !light) throw new Error('app.css: theme blocks not found');
  // Declarations can span lines (font stacks, shadows); keep whole statements,
  // and only the colors, since sizes and fonts don't change with the theme.
  const colors = (block) =>
    (block.match(/\s*--[\w-]+:[^;]*;/g) ?? []).filter((s) => !/--(font|radius|ease|fast|normal|page|gutter)/.test(s)).join('');
  return (
    banner('web/src/app.css') +
    css +
    `\n/* Board scopes (prototype only): the same tokens on any element. */\n` +
    `[data-theme="light"] {${colors(light[1])}\n  color-scheme: light;\n}\n` +
    `[data-theme="dark"] {${colors(dark[1])}\n  color-scheme: dark;\n}\n`
  );
}

/** Both dictionaries from i18n.svelte.ts, evaluated as plain object literals. */
function i18n() {
  const src = read(join(web, 'src/lib/i18n.svelte.ts'));
  const zh = src.match(/const zh = (\{[\s\S]*?\n\});/);
  const en = src.match(/const en: [^=]+= (\{[\s\S]*?\n\});/);
  if (!zh || !en) throw new Error('i18n.svelte.ts: dictionaries not found');
  const obj = (s) => new Function(`return ${s}`)();
  const dicts = { zh: obj(zh[1]), en: obj(en[1]) };
  return banner('web/src/lib/i18n.svelte.ts') + `window.SANI_I18N = ${JSON.stringify(dicts, null, 1)};\n`;
}

/** Icon paths from Icon.svelte's module script, with the helpers it uses. */
function icons() {
  const src = read(join(web, 'src/components/Icon.svelte'));
  const mod = src.match(/<script lang="ts" module>([\s\S]*?)<\/script>/);
  if (!mod) throw new Error('Icon.svelte: module script not found');
  const body = mod[1]
    .replace(/\(cx: number, cy: number, r: number\)/, '(cx, cy, r)')
    .replace(/\(x: number, y: number, w: number, h: number, r: number\)/, '(x, y, w, h, r)')
    .replace(/\}\s*satisfies [^;]+;/, '};')
    .replace(/export type[^;]+;/, '');
  const map = new Function(`${body}\nreturn icons;`)();
  return banner('web/src/components/Icon.svelte') + `window.SANI_ICONS = ${JSON.stringify(map, null, 1)};\n`;
}

/** uqr (MIT, the encoder production uses) wrapped as a global. */
function uqr() {
  const pkg = JSON.parse(read(join(web, 'node_modules/uqr/package.json')));
  const code = read(join(web, 'node_modules/uqr/dist/index.cjs'));
  return (
    banner(`web/node_modules/uqr@${pkg.version} (MIT, ${pkg.repository?.url ?? 'unjs/uqr'})`) +
    `(function () {\nvar exports = {};\n${code}\nwindow.uqr = exports;\n})();\n`
  );
}

/**
 * The visitor pages the Go server renders (web.go pageTemplate, sharepage.go
 * sharePage): their stylesheets verbatim and both languages' copy.
 */
function visitor() {
  const server = join(repo, 'internal/server');
  const web = read(join(server, 'web.go'));
  const share = read(join(server, 'sharepage.go'));
  const style = (src, name) => {
    const m = src.match(new RegExp(`const ${name} = \`[\\s\\S]*?<style>\\n([\\s\\S]*?)</style>`));
    if (!m) throw new Error(`${name}: <style> not found`);
    return m[1];
  };
  const block = (src, name) => {
    const m = src.match(new RegExp(`var ${name} = map\\[string\\][^{]+\\{\\n([\\s\\S]*?)\\n\\}\\n`));
    if (!m) throw new Error(`${name} not found`);
    const out = {};
    for (const [, lang, body] of m[1].matchAll(/\t"(\w+)": \{\n([\s\S]*?)\n\t\},/g)) out[lang] = body;
    return out;
  };
  const kinds = { pageNotFound: 'notfound', pageGone: 'gone', pageError: 'error', pageShareNotFound: 'share-notfound', pageShareGone: 'share-gone' };
  const pageCopy = {};
  for (const [lang, body] of Object.entries(block(web, 'pageCopy'))) {
    pageCopy[lang] = {};
    for (const [, kind, args] of body.matchAll(/(page\w+):\s*\{(".*")\},/g)) {
      const [title, heading, text] = JSON.parse(`[${args}]`);
      pageCopy[lang][kinds[kind]] = { title, heading, body: text };
    }
  }
  const pageStatus = {};
  for (const [, kind, code] of web.matchAll(/(page\w+):\s+http\.Status(\w+),/g)) pageStatus[kinds[kind]] = { NotFound: 404, Gone: 410, InternalServerError: 500 }[code];
  const shareCopy = {};
  for (const [lang, body] of Object.entries(block(share, 'shareCopy'))) {
    shareCopy[lang] = Object.fromEntries([...body.matchAll(/(\w+): "([^"]*)"/g)].map(([, k, v]) => [k, v]));
  }
  const icon = share.match(/<svg width="40"[\s\S]*?<\/svg>/);
  if (!icon) throw new Error('sharePage: file icon not found');
  const data = { pageCss: style(web, 'pageTemplate'), pageCopy, pageStatus, shareCss: style(share, 'sharePage'), shareCopy, fileIcon: icon[0] };
  return banner('internal/server/web.go and sharepage.go') + `window.SANI_VISITOR = ${JSON.stringify(data, null, 1)};\n`;
}

const fonts = [
  ['@fontsource-variable/inter/files/inter-latin-wght-normal.woff2', 'inter-latin-wght-normal.woff2'],
  ['@fontsource-variable/inter/files/inter-latin-ext-wght-normal.woff2', 'inter-latin-ext-wght-normal.woff2'],
  ['@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-400-normal.woff2', 'ibm-plex-mono-latin-400-normal.woff2'],
  ['@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-500-normal.woff2', 'ibm-plex-mono-latin-500-normal.woff2'],
];

const outputs = [
  ['src/gen/tokens.css', tokens],
  ['src/gen/i18n.js', i18n],
  ['src/gen/icons.js', icons],
  ['src/gen/uqr.js', uqr],
  ['src/gen/visitor.js', visitor],
];

let drift = 0;
for (const [rel, make] of outputs) {
  const file = join(project, rel);
  const next = make();
  if (check) {
    if (!existsSync(file) || read(file) !== next) {
      console.error(`drift: ${rel} differs from production source`);
      drift++;
    }
    continue;
  }
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, next);
  console.log('wrote', rel);
}
for (const [from, to] of fonts) {
  const src = readFileSync(join(web, 'node_modules', from));
  const file = join(project, 'src/fonts', to);
  if (check) {
    if (!existsSync(file) || !readFileSync(file).equals(src)) {
      console.error(`drift: src/fonts/${to} differs from ${from}`);
      drift++;
    }
    continue;
  }
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, src);
  console.log('wrote', `src/fonts/${to}`);
}
if (check) {
  if (drift) process.exit(1);
  console.log(`in sync (${outputs.length + fonts.length} files)`);
}
