// Category, address and visit vocabulary applies to every shared surface.
Object.assign(window.SANI_I18N.zh, {
  'keys.new':'聚焦创建区域', 'settings.exportHint':'包含每条链接的设置与访问总数，不含分享的文本和文件。',
  'filter.url':'链接', 'filter.text':'文本', 'filter.file':'文件',
  'list.col.link':'分享地址', 'list.col.clicks':'访问', 'sort.clicks':'访问最多',
  'list.copyShort':'复制分享地址', 'keys.copy':'复制分享地址',
  'list.emptyTitle':'还没有内容',
  'list.emptyBody':'在上方选择链接、文本或文件，创建你的第一条内容。',
  'list.emptyPaste':'创建链接时，也可以在页面空白处按 {key} 粘贴网址。',
  'list.noneUrl':'还没有链接', 'list.noneText':'还没有文本', 'list.noneFile':'还没有文件',
  'list.spark':'近 14 天共 {n} 次访问', 'detail.clicks':'访问',
  'detail.chart':'每日访问', 'chart.table':'每日访问数据',
  'settings.domain':'分享域名',
  'settings.domainHint':'生成链接、文本和文件的分享地址时使用的域名。留空则使用当前访问地址（{origin}）。',
  'settings.domainSaved':'已更新分享域名',
  'setup.lead':'先输入启动日志里的设置码，再设置以后登录用的密码。',
});
Object.assign(window.SANI_I18N.en, {
  'keys.new':'Focus creation form', 'settings.exportHint':'Includes settings and total visits for each URL link. Shared text and files are excluded.',
  'filter.url':'Links', 'filter.text':'Text', 'filter.file':'Files',
  'list.col.link':'Share URL', 'list.col.clicks':'Visits', 'sort.clicks':'Most visits',
  'list.copyShort':'Copy share URL', 'keys.copy':'Copy share URL',
  'list.emptyTitle':'No items yet',
  'list.emptyBody':'Choose Links, Text or Files above to create your first item.',
  'list.emptyPaste':'When creating a link, press {key} on an empty area of the page to paste a URL.',
  'list.noneUrl':'No links yet', 'list.noneText':'No text yet', 'list.noneFile':'No files yet',
  'list.spark':'{n} visits in the last 14 days',
  'list.spark.one':'1 visit in the last 14 days', 'list.spark.other':'{n} visits in the last 14 days',
  'detail.clicks':'Visits',
  'detail.chart':'Daily visits', 'chart.table':'Daily visit data',
  'settings.domain':'Share domain',
  'settings.domainHint':'The domain used for link, text and file share URLs. Leave blank to use the current address ({origin}).',
  'settings.domainSaved':'Share domain updated',
  'setup.lead':'Enter the setup code from the startup log, then set the password you will use to sign in.',
});
